services:
  s3-storage:
    image: adobe/s3mock:latest
    container_name: local_s3_storage
    ports:
      - "18000:9090"
    environment:
      initialBuckets: shopeefood-raw-data
    volumes:
      - ./data/s3_storage:/s3mock-root

volumes:
  s3_data: