[project]
name = "project-ady201m-group1-main"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "pandas>=3.0.6",
    "playwright>=1.63.0",
    "requests>=2.34.2",
    "scrapetube>=2.6.0",
    "selenium>=4.49.0",
    "webdriver-manager>=4.1.2",
    "youtube-comment-downloader>=0.1.83",
]
